import { Position } from "../../common/grid";

export const plus: Array<Position> = [
  { row: 1, col: 1 },
  { row: 0, col: 1 },
  { row: 1, col: 0 },
  { row: 2, col: 1 },
  { row: 1, col: 2 },
];

export const minus: Array<Position> = [
  { row: 1, col: 1 },
  { row: 1, col: 0 },
  { row: 1, col: 2 },
];

export const dot_1: Array<Position> = [{ row: 0, col: 0 }];

export const dot_2_wide: Array<Position> = [
  { row: 0, col: 0 },
  { row: 0, col: 1 },
];
export const dot_2_high: Array<Position> = [
  { row: 0, col: 0 },
  { row: 1, col: 0 },
];

export const divide: Array<Position> = [
  { row: 0, col: 1 },
  { row: 2, col: 1 },
];

export const l: Array<Position> = [
  { row: 0, col: 1 },
  { row: 1, col: 1 },
  { row: 2, col: 1 },
];

export const heart: Array<Position> = [
  { row: 0, col: 1 },
  { row: 0, col: 3 },
  { row: 1, col: 0 },
  { row: 1, col: 1 },
  { row: 1, col: 2 },
  { row: 1, col: 3 },
  { row: 1, col: 4 },
  { row: 2, col: 0 },
  { row: 2, col: 1 },
  { row: 2, col: 2 },
  { row: 2, col: 3 },
  { row: 2, col: 4 },
  { row: 3, col: 1 },
  { row: 3, col: 2 },
  { row: 3, col: 3 },
  { row: 4, col: 2 },
];

export const love: Array<Position> = [
  { row: 0, col: 0 },
  { row: 0, col: 1 },
  { row: 0, col: 4 },
  { row: 0, col: 7 },
  { row: 0, col: 8 },
  { row: 0, col: 9 },
  { row: 1, col: 0 },
  { row: 1, col: 6 },
  { row: 1, col: 8 },
  { row: 1, col: 9 },
  { row: 2, col: 0 },
  { row: 2, col: 6 },
  { row: 2, col: 8 },
  { row: 2, col: 9 },
  { row: 3, col: 0 },
  { row: 3, col: 8 },
  { row: 3, col: 9 },
  { row: 4, col: 0 },
  { row: 4, col: 1 },
  { row: 4, col: 7 },
  { row: 4, col: 8 },
  { row: 4, col: 9 },
  { row: 5, col: 0 },
  { row: 5, col: 1 },
  { row: 5, col: 2 },
  { row: 5, col: 6 },
  { row: 5, col: 7 },
  { row: 5, col: 8 },
  { row: 5, col: 9 },
  { row: 6, col: 0 },
  { row: 6, col: 1 },
  { row: 6, col: 2 },
  { row: 6, col: 3 },
  { row: 6, col: 5 },
  { row: 6, col: 6 },
  { row: 6, col: 7 },
  { row: 6, col: 9 },
  { row: 7, col: 0 },
  { row: 7, col: 2 },
  { row: 7, col: 3 },
  { row: 7, col: 4 },
  { row: 7, col: 5 },
  { row: 7, col: 6 },
  { row: 7, col: 8 },
  { row: 8, col: 1 },
  { row: 8, col: 3 },
  { row: 8, col: 4 },
  { row: 8, col: 6 },
  { row: 8, col: 7 },
  { row: 8, col: 9 },
  { row: 9, col: 0 },
  { row: 9, col: 2 },
  { row: 9, col: 3 },
  { row: 9, col: 5 },
  { row: 9, col: 7 },
  { row: 9, col: 8 },
  { row: 9, col: 9 },
];

export const duck: Array<Position> = [
  { row: 0, col: 1 },
  { row: 0, col: 2 },
  { row: 0, col: 3 },
  { row: 1, col: 0 },
  { row: 1, col: 1 },
  { row: 1, col: 3 },
  { row: 2, col: 1 },
  { row: 2, col: 2 },
  { row: 2, col: 3 },
  { row: 2, col: 6 },
  { row: 2, col: 7 },
  { row: 3, col: 2 },
  { row: 3, col: 3 },
  { row: 3, col: 6 },
  { row: 3, col: 7 },
  { row: 4, col: 2 },
  { row: 4, col: 3 },
  { row: 4, col: 4 },
  { row: 4, col: 5 },
  { row: 4, col: 6 },
  { row: 4, col: 7 },
  { row: 5, col: 0 },
  { row: 5, col: 2 },
  { row: 5, col: 3 },
  { row: 5, col: 4 },
  { row: 5, col: 5 },
  { row: 5, col: 6 },
  { row: 6, col: 0 },
  { row: 6, col: 1 },
  { row: 6, col: 2 },
  { row: 6, col: 3 },
  { row: 6, col: 4 },
  { row: 6, col: 5 },
  { row: 7, col: 4 },
  { row: 8, col: 3 },
  { row: 8, col: 4 },
];
